import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-1-length-time', unitId: 'g3-1-length-time', conceptIds: ['g3-1-length-time-length-time'], primaryStandard: '[4수03-13]', connectedStandards: ['[4수03-14]', '[4수03-15]', '[4수03-16]'], representations: ['text', 'equation', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-length-time-bars', visualDescription: '길이와 시간을 각각 같은 단위의 막대 길이로 나타낸 그림' }
const MIS = ['g3-length-unit-scale', 'g3-time-base-ten']

export const G3_1_LENGTH_TIME_FAMILY_RECIPES = [
  { familyId: 'g3-1-length-time-trip-conversion', cognitiveDomain: 'applying' as const, reasoningPattern: 'representation_shift' as const, estimatedSteps: 4, modelId: 'g3-length-time-conversion-v1', unknownRole: 'two-converted-measures', requiredStudentActions: ['interpret_context', 'convert_representation', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ km: 2, m: 350, hour: 1, minute: 20 }, { km: 4, m: 75, hour: 2, minute: 5 }, { km: 7, m: 640, hour: 3, minute: 45 }] },
  { familyId: 'g3-1-length-time-missing-distance', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 2, modelId: 'g3-length-missing-distance-v1', unknownRole: 'remaining-distance', requiredStudentActions: ['interpret_context', 'infer_missing_value', 'verify_result'] as const, misconceptionRefs: ['g3-length-unit-scale'], cases: [{ totalM: 1250, firstM: 480 }, { totalM: 2340, firstM: 875 }, { totalM: 4080, firstM: 1695 }] },
  { familyId: 'g3-1-length-time-elapsed-time', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'multi_step' as const, estimatedSteps: 4, modelId: 'g3-time-elapsed-seconds-v1', unknownRole: 'elapsed-seconds', requiredStudentActions: ['convert_representation', 'choose_model', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: ['g3-time-base-ten'], cases: [{ startMinute: 1, startSecond: 35, endMinute: 3, endSecond: 10 }, { startMinute: 2, startSecond: 48, endMinute: 5, endSecond: 7 }, { startMinute: 4, startSecond: 55, endMinute: 8, endSecond: 20 }] },
  { familyId: 'g3-1-length-time-unit-claim-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 3, modelId: 'g3-length-conversion-error-v1', unknownRole: 'correct-millimetres', requiredStudentActions: ['convert_representation', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: ['g3-length-unit-scale'], cases: [{ cm: 4, mm: 7, claimedMm: 407 }, { cm: 12, mm: 5, claimedMm: 1250 }, { cm: 23, mm: 8, claimedMm: 2380 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, conceptIds: [...common.conceptIds], connectedStandards: [...common.connectedStandards], requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
