import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-1-multiply', unitId: 'g3-1-multiply', conceptIds: ['g3-1-multiply-multiplication'], primaryStandard: '[4수01-04]', connectedStandards: [], representations: ['text', 'equation', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-multiplication-array', visualDescription: '곱셈의 묶음과 남은 양을 크기에 맞게 나타낸 그림' }
const MIS = ['g3-multiply-place-value', 'g3-multiply-add-factors']

export const G3_1_MULTIPLY_FAMILY_RECIPES = [
  { familyId: 'g3-1-multiply-two-step-total', cognitiveDomain: 'applying' as const, reasoningPattern: 'multi_step' as const, estimatedSteps: 3, modelId: 'g3-multiply-two-step-v1', unknownRole: 'remaining-total', requiredStudentActions: ['interpret_context', 'choose_model', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ boxes: 6, each: 24, removed: 17 }, { boxes: 7, each: 32, removed: 29 }, { boxes: 8, each: 45, removed: 64 }] },
  { familyId: 'g3-1-multiply-missing-groups', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 2, modelId: 'g3-multiply-inverse-v1', unknownRole: 'group-count', requiredStudentActions: ['infer_missing_value', 'convert_representation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ total: 144, each: 24 }, { total: 224, each: 32 }, { total: 360, each: 45 }] },
  { familyId: 'g3-1-multiply-strategy-compare', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'compare_methods' as const, estimatedSteps: 3, modelId: 'g3-multiply-distributive-v1', unknownRole: 'strategy-validity', requiredStudentActions: ['compare_strategies', 'evaluate_claim', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ a: 23, b: 4, split: 2, claimed: 92 }, { a: 34, b: 6, split: 3, claimed: 194 }, { a: 42, b: 7, split: 5, claimed: 294 }] },
  { familyId: 'g3-1-multiply-product-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 2, modelId: 'g3-multiply-product-error-v1', unknownRole: 'correct-product', requiredStudentActions: ['evaluate_claim', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ a: 24, b: 3, claimed: 62 }, { a: 36, b: 5, claimed: 160 }, { a: 48, b: 7, claimed: 326 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
