import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-1-division', unitId: 'g3-1-division', conceptIds: ['g3-1-division-division-meaning'], primaryStandard: '[4수01-05]', connectedStandards: ['[4수01-06]'], representations: ['text', 'equation', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-division-groups', visualDescription: '전체와 같은 수의 묶음을 양에 맞게 나타낸 그림' }
const MIS = ['g3-division-multiply-instead', 'g3-division-group-size-count']

export const G3_1_DIVISION_FAMILY_RECIPES = [
  { familyId: 'g3-1-division-sharing-plan', cognitiveDomain: 'applying' as const, reasoningPattern: 'model_and_check' as const, estimatedSteps: 2, modelId: 'g3-division-sharing-v1', unknownRole: 'each-share', requiredStudentActions: ['interpret_context', 'choose_model', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ total: 24, groups: 6 }, { total: 42, groups: 7 }, { total: 72, groups: 8 }] },
  { familyId: 'g3-1-division-missing-total', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 2, modelId: 'g3-division-inverse-v1', unknownRole: 'whole', requiredStudentActions: ['infer_missing_value', 'convert_representation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ groups: 5, each: 7 }, { groups: 8, each: 6 }, { groups: 9, each: 8 }] },
  { familyId: 'g3-1-division-model-check', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'compare_methods' as const, estimatedSteps: 3, modelId: 'g3-division-model-check-v1', unknownRole: 'claim-validity', requiredStudentActions: ['choose_model', 'compare_strategies', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ total: 36, groups: 6, claimedEach: 6 }, { total: 48, groups: 8, claimedEach: 7 }, { total: 63, groups: 7, claimedEach: 9 }] },
  { familyId: 'g3-1-division-fact-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 2, modelId: 'g3-division-fact-error-v1', unknownRole: 'correct-quotient', requiredStudentActions: ['evaluate_claim', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ total: 32, divisor: 4, claimed: 6 }, { total: 54, divisor: 6, claimed: 8 }, { total: 81, divisor: 9, claimed: 7 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, conceptIds: [...common.conceptIds], connectedStandards: [...common.connectedStandards], requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
