import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-1-fraction-decimal', unitId: 'g3-1-fraction-decimal', conceptIds: ['g3-1-fraction-decimal-fraction-decimal'], primaryStandard: '[4수01-09]', connectedStandards: ['[4수01-12]'], representations: ['text', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-fraction-tenths-strip', visualDescription: '전체를 10등분한 양과 소수 한 자리 수의 관계를 나타낸 그림' }
const MIS = ['g3-fraction-count-parts', 'g3-decimal-whole-number']

export const G3_1_FRACTION_DECIMAL_FAMILY_RECIPES = [
  { familyId: 'g3-1-fraction-decimal-tenths-conversion', cognitiveDomain: 'applying' as const, reasoningPattern: 'representation_shift' as const, estimatedSteps: 2, modelId: 'g3-tenths-conversion-v1', unknownRole: 'equivalent-fraction-decimal', requiredStudentActions: ['interpret_context', 'convert_representation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ shaded: 2 }, { shaded: 5 }, { shaded: 9 }] },
  { familyId: 'g3-1-fraction-decimal-missing-parts', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 2, modelId: 'g3-fraction-missing-parts-v1', unknownRole: 'unshaded-parts', requiredStudentActions: ['infer_missing_value', 'choose_model', 'verify_result'] as const, misconceptionRefs: ['g3-fraction-count-parts'], cases: [{ total: 10, shaded: 2 }, { total: 10, shaded: 6 }, { total: 10, shaded: 9 }] },
  { familyId: 'g3-1-fraction-decimal-representation-check', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'model_and_check' as const, estimatedSteps: 2, modelId: 'g3-fraction-decimal-check-v1', unknownRole: 'equivalence-validity', requiredStudentActions: ['convert_representation', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ numerator: 3, decimalNumerator: 3 }, { numerator: 6, decimalNumerator: 4 }, { numerator: 9, decimalNumerator: 9 }] },
  { familyId: 'g3-1-fraction-decimal-decimal-claim-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 2, modelId: 'g3-decimal-claim-error-v1', unknownRole: 'correct-decimal', requiredStudentActions: ['convert_representation', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: ['g3-decimal-whole-number'], cases: [{ numerator: 2, claimedDecimalNumerator: 5 }, { numerator: 7, claimedDecimalNumerator: 4 }, { numerator: 9, claimedDecimalNumerator: 6 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, conceptIds: [...common.conceptIds], connectedStandards: [...common.connectedStandards], requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
