import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-2-division', unitId: 'g3-2-division', conceptIds: ['g3-2-division-division-remainder'], primaryStandard: '[4수01-06]', connectedStandards: [], representations: ['text', 'equation', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-division-remainder-bars', visualDescription: '전체를 같은 수의 묶음과 남는 양으로 나누어 나타낸 그림' }
const MIS = ['g3-remainder-too-large', 'g3-division-ignore-remainder']

export const G3_2_DIVISION_FAMILY_RECIPES = [
  { familyId: 'g3-2-division-share-remainder', cognitiveDomain: 'applying' as const, reasoningPattern: 'model_and_check' as const, estimatedSteps: 3, modelId: 'g3-division-share-remainder-v1', unknownRole: 'quotient-and-remainder', requiredStudentActions: ['interpret_context', 'choose_model', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ total: 29, divisor: 4 }, { total: 47, divisor: 6 }, { total: 68, divisor: 9 }] },
  { familyId: 'g3-2-division-missing-dividend', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 3, modelId: 'g3-division-missing-dividend-v1', unknownRole: 'dividend', requiredStudentActions: ['infer_missing_value', 'convert_representation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ divisor: 4, quotient: 7, remainder: 1 }, { divisor: 6, quotient: 8, remainder: 5 }, { divisor: 9, quotient: 7, remainder: 5 }] },
  { familyId: 'g3-2-division-remainder-constraint', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'constraint' as const, estimatedSteps: 2, modelId: 'g3-remainder-constraint-v1', unknownRole: 'valid-remainder', requiredStudentActions: ['test_constraint', 'compare_strategies', 'verify_result'] as const, misconceptionRefs: ['g3-remainder-too-large'], cases: [{ divisor: 4, candidate: 3 }, { divisor: 7, candidate: 5 }, { divisor: 9, candidate: 8 }] },
  { familyId: 'g3-2-division-quotient-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 3, modelId: 'g3-division-quotient-error-v1', unknownRole: 'correct-quotient-remainder', requiredStudentActions: ['evaluate_claim', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ total: 35, divisor: 4, claimedQuotient: 9 }, { total: 58, divisor: 7, claimedQuotient: 7 }, { total: 76, divisor: 9, claimedQuotient: 9 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
