import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-2-graph', unitId: 'g3-2-graph', conceptIds: ['g3-2-graph-graph'], primaryStandard: '[4수04-01]', connectedStandards: ['[4수04-03]'], representations: ['text', 'table', 'graph'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-data-bar-graph', visualDescription: '표의 세 항목 값을 같은 눈금의 막대 높이로 나타낸 그래프' }
const MIS = ['g3-graph-scale-reading', 'g3-graph-label-sufficiency']

export const G3_2_GRAPH_FAMILY_RECIPES = [
  { familyId: 'g3-2-graph-table-to-bar', cognitiveDomain: 'applying' as const, reasoningPattern: 'representation_shift' as const, estimatedSteps: 2, modelId: 'g3-table-to-bar-v1', unknownRole: 'target-bar-height', requiredStudentActions: ['interpret_context', 'convert_representation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ a: 5, b: 8, c: 3, target: '나' }, { a: 12, b: 7, c: 10, target: '가' }, { a: 9, b: 14, c: 16, target: '다' }] },
  { familyId: 'g3-2-graph-missing-category', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 3, modelId: 'g3-graph-missing-category-v1', unknownRole: 'missing-bar-value', requiredStudentActions: ['select_relevant_data', 'infer_missing_value', 'verify_result'] as const, misconceptionRefs: ['g3-graph-scale-reading'], cases: [{ total: 24, a: 7, b: 9 }, { total: 35, a: 12, b: 8 }, { total: 48, a: 17, b: 14 }] },
  { familyId: 'g3-2-graph-claim-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 2, modelId: 'g3-graph-max-claim-error-v1', unknownRole: 'actual-maximum-category', requiredStudentActions: ['interpret_context', 'compare_strategies', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: ['g3-graph-scale-reading'], cases: [{ a: 6, b: 11, c: 8, claimedCategory: '가' }, { a: 15, b: 9, c: 13, claimedCategory: '나' }, { a: 7, b: 12, c: 18, claimedCategory: '나' }] },
  { familyId: 'g3-2-graph-data-sufficiency', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'data_sufficiency' as const, estimatedSteps: 2, modelId: 'g3-graph-label-sufficiency-v1', unknownRole: 'evidence-sufficiency', requiredStudentActions: ['select_relevant_data', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: ['g3-graph-label-sufficiency'], cases: [{ a: 6, b: 10, hasCategoryLabels: true }, { a: 9, b: 14, hasCategoryLabels: false }, { a: 12, b: 7, hasCategoryLabels: true }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, conceptIds: [...common.conceptIds], connectedStandards: [...common.connectedStandards], requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
