import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-2-capacity-weight', unitId: 'g3-2-capacity-weight', conceptIds: ['g3-2-capacity-weight-capacity-weight'], primaryStandard: '[4수03-17]', connectedStandards: ['[4수03-18]', '[4수03-19]', '[4수03-20]', '[4수03-21]', '[4수03-22]', '[4수03-23]'], representations: ['text', 'equation', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-capacity-weight-bars', visualDescription: '들이와 무게를 각각 같은 작은 단위의 막대 길이로 나타낸 그림' }
const MIS = ['g3-capacity-unit-scale', 'g3-weight-unit-scale']

export const G3_2_CAPACITY_WEIGHT_FAMILY_RECIPES = [
  { familyId: 'g3-2-capacity-weight-measure-pair', cognitiveDomain: 'applying' as const, reasoningPattern: 'representation_shift' as const, estimatedSteps: 4, modelId: 'g3-measure-pair-conversion-v1', unknownRole: 'two-small-unit-measures', requiredStudentActions: ['interpret_context', 'convert_representation', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ liters: 1, milliliters: 250, kg: 3, g: 400 }, { liters: 2, milliliters: 75, kg: 5, g: 80 }, { liters: 4, milliliters: 900, kg: 8, g: 650 }] },
  { familyId: 'g3-2-capacity-weight-missing-capacity', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 2, modelId: 'g3-capacity-missing-v1', unknownRole: 'remaining-capacity', requiredStudentActions: ['interpret_context', 'infer_missing_value', 'verify_result'] as const, misconceptionRefs: ['g3-capacity-unit-scale'], cases: [{ totalMl: 1250, usedMl: 475 }, { totalMl: 2300, usedMl: 850 }, { totalMl: 4800, usedMl: 2675 }] },
  { familyId: 'g3-2-capacity-weight-conversion-compare', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'compare_methods' as const, estimatedSteps: 3, modelId: 'g3-capacity-conversion-check-v1', unknownRole: 'conversion-validity', requiredStudentActions: ['convert_representation', 'compare_strategies', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: ['g3-capacity-unit-scale'], cases: [{ liters: 1, milliliters: 300, claimedMl: 1300 }, { liters: 2, milliliters: 50, claimedMl: 2500 }, { liters: 4, milliliters: 725, claimedMl: 4725 }] },
  { familyId: 'g3-2-capacity-weight-weight-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 3, modelId: 'g3-weight-conversion-error-v1', unknownRole: 'correct-grams', requiredStudentActions: ['convert_representation', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: ['g3-weight-unit-scale'], cases: [{ kg: 2, g: 350, claimedG: 235 }, { kg: 5, g: 80, claimedG: 5800 }, { kg: 7, g: 625, claimedG: 76250 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, conceptIds: [...common.conceptIds], connectedStandards: [...common.connectedStandards], requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
