import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-2-multiply', unitId: 'g3-2-multiply', conceptIds: ['g3-2-multiply-multiplication'], primaryStandard: '[4수01-04]', connectedStandards: [], representations: ['text', 'equation', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-two-digit-multiplication-bars', visualDescription: '두 자리 수 곱셈의 묶음과 낱개를 크기에 맞게 나타낸 그림' }
const MIS = ['g3-multiply-partial-product', 'g3-multiply-place-value']

export const G3_2_MULTIPLY_FAMILY_RECIPES = [
  { familyId: 'g3-2-multiply-box-total', cognitiveDomain: 'applying' as const, reasoningPattern: 'multi_step' as const, estimatedSteps: 3, modelId: 'g3-multiply-box-total-v1', unknownRole: 'combined-total', requiredStudentActions: ['interpret_context', 'choose_model', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ packs: 12, each: 14, extra: 7 }, { packs: 23, each: 16, extra: 9 }, { packs: 31, each: 24, extra: 15 }] },
  { familyId: 'g3-2-multiply-missing-factor', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 3, modelId: 'g3-multiply-missing-factor-v1', unknownRole: 'missing-factor', requiredStudentActions: ['infer_missing_value', 'convert_representation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ total: 168, factor: 12 }, { total: 368, factor: 23 }, { total: 744, factor: 31 }] },
  { familyId: 'g3-2-multiply-distributive-check', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'compare_methods' as const, estimatedSteps: 4, modelId: 'g3-multiply-distributive-check-v1', unknownRole: 'strategy-validity', requiredStudentActions: ['compare_strategies', 'evaluate_claim', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ a: 14, b: 12, split: 10, claimed: 168 }, { a: 16, b: 23, split: 20, claimed: 358 }, { a: 24, b: 31, split: 30, claimed: 744 }] },
  { familyId: 'g3-2-multiply-product-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 3, modelId: 'g3-two-digit-product-error-v1', unknownRole: 'correct-product', requiredStudentActions: ['evaluate_claim', 'execute_calculation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ a: 13, b: 24, claimed: 302 }, { a: 21, b: 35, claimed: 715 }, { a: 32, b: 46, claimed: 1462 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
