import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-2-circle', unitId: 'g3-2-circle', conceptIds: ['g3-2-circle-circle'], primaryStandard: '[4수03-06]', connectedStandards: ['[4수03-07]'], representations: ['text', 'diagram'] as const, visualMode: 'circle' as const, visualGeneratorId: 'g3-circle-radius', visualDescription: '원의 중심에서 원 위까지 반지름을 실제 비율로 나타낸 그림' }
const MIS = ['g3-circle-radius-diameter', 'g3-compass-opening-diameter']

export const G3_2_CIRCLE_FAMILY_RECIPES = [
  { familyId: 'g3-2-circle-compass-diameter', cognitiveDomain: 'applying' as const, reasoningPattern: 'representation_shift' as const, estimatedSteps: 2, modelId: 'g3-circle-compass-diameter-v1', unknownRole: 'diameter', requiredStudentActions: ['interpret_context', 'convert_representation', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ radius: 3 }, { radius: 7 }, { radius: 12 }] },
  { familyId: 'g3-2-circle-missing-radius', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'inverse' as const, estimatedSteps: 2, modelId: 'g3-circle-missing-radius-v1', unknownRole: 'radius', requiredStudentActions: ['infer_missing_value', 'convert_representation', 'verify_result'] as const, misconceptionRefs: ['g3-circle-radius-diameter'], cases: [{ diameter: 8 }, { diameter: 14 }, { diameter: 24 }] },
  { familyId: 'g3-2-circle-construction-constraint', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'constraint' as const, estimatedSteps: 3, modelId: 'g3-circle-construction-constraint-v1', unknownRole: 'construction-validity', requiredStudentActions: ['choose_model', 'test_constraint', 'verify_result'] as const, misconceptionRefs: ['g3-compass-opening-diameter'], cases: [{ targetDiameter: 10, opening: 5 }, { targetDiameter: 14, opening: 6 }, { targetDiameter: 18, opening: 9 }] },
  { familyId: 'g3-2-circle-property-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 2, modelId: 'g3-circle-property-error-v1', unknownRole: 'correct-diameter', requiredStudentActions: ['evaluate_claim', 'convert_representation', 'verify_result'] as const, misconceptionRefs: ['g3-circle-radius-diameter'], cases: [{ radius: 4, claimedDiameter: 4 }, { radius: 9, claimedDiameter: 27 }, { radius: 15, claimedDiameter: 20 }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, conceptIds: [...common.conceptIds], connectedStandards: [...common.connectedStandards], requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
