import { createGrade3ApplicationFamilyRecipe } from './g3-family-support'

const common = { packId: 'pack-g3-2-fraction', unitId: 'g3-2-fraction', conceptIds: ['g3-2-fraction-fraction'], primaryStandard: '[4수01-10]', connectedStandards: ['[4수01-11]'], representations: ['text', 'diagram'] as const, visualMode: 'bars' as const, visualGeneratorId: 'g3-fraction-comparison-strip', visualDescription: '같은 크기의 전체를 같은 분모로 나눈 분수 막대 그림' }
const MIS = ['g3-fraction-form-whole', 'g3-fraction-larger-denominator']

export const G3_2_FRACTION_FAMILY_RECIPES = [
  { familyId: 'g3-2-fraction-form-and-compare', cognitiveDomain: 'applying' as const, reasoningPattern: 'model_and_check' as const, estimatedSteps: 3, modelId: 'g3-fraction-form-compare-v1', unknownRole: 'larger-representation', requiredStudentActions: ['interpret_context', 'convert_representation', 'compare_strategies', 'verify_result'] as const, misconceptionRefs: MIS, cases: [{ whole: 1, numerator: 2, denominator: 5, otherNumerator: 6 }, { whole: 2, numerator: 1, denominator: 4, otherNumerator: 9 }, { whole: 1, numerator: 3, denominator: 8, otherNumerator: 11 }] },
  { familyId: 'g3-2-fraction-missing-numerator', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'constraint' as const, estimatedSteps: 2, modelId: 'g3-fraction-numerator-constraint-v1', unknownRole: 'valid-numerator', requiredStudentActions: ['test_constraint', 'compare_strategies', 'verify_result'] as const, misconceptionRefs: ['g3-fraction-larger-denominator'], cases: [{ denominator: 7, lowNumerator: 2, highNumerator: 6, candidate: 4 }, { denominator: 9, lowNumerator: 3, highNumerator: 8, candidate: 5 }, { denominator: 10, lowNumerator: 4, highNumerator: 9, candidate: 7 }] },
  { familyId: 'g3-2-fraction-representation-shift', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'representation_shift' as const, estimatedSteps: 3, modelId: 'g3-mixed-improper-shift-v1', unknownRole: 'improper-fraction', requiredStudentActions: ['convert_representation', 'choose_model', 'verify_result'] as const, misconceptionRefs: ['g3-fraction-form-whole'], cases: [{ whole: 1, numerator: 2, denominator: 5 }, { whole: 2, numerator: 3, denominator: 7 }, { whole: 3, numerator: 4, denominator: 9 }] },
  { familyId: 'g3-2-fraction-comparison-error', cognitiveDomain: 'reasoning' as const, reasoningPattern: 'error_analysis' as const, estimatedSteps: 2, modelId: 'g3-fraction-comparison-error-v1', unknownRole: 'correct-comparison', requiredStudentActions: ['compare_strategies', 'evaluate_claim', 'verify_result'] as const, misconceptionRefs: ['g3-fraction-larger-denominator'], cases: [{ leftNumerator: 3, rightNumerator: 5, denominator: 8, claimed: '왼쪽이 더 커요' }, { leftNumerator: 7, rightNumerator: 4, denominator: 9, claimed: '오른쪽이 더 커요' }, { leftNumerator: 6, rightNumerator: 6, denominator: 10, claimed: '왼쪽이 더 커요' }] },
].map((definition) => createGrade3ApplicationFamilyRecipe({ ...common, ...definition, conceptIds: [...common.conceptIds], connectedStandards: [...common.connectedStandards], requiredStudentActions: [...definition.requiredStudentActions], misconceptionRefs: [...definition.misconceptionRefs], cases: definition.cases }))
